language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  # By default postgresql-9.1 is installed but there is issue related:
  #  https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
  # Better use higher PostgreSQL version
  postgresql: "9.5"
  apt:
#    sources:
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml
#     For wkhtmltopdf, see the env section below


env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"

virtualenv:
    system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
